config/routes.rb
Rails.application.routes.draw do

 devise_for :users, :controllers => { registrations: 'registrations' }
  get 'dashboard', to: 'users#dashboard'
  root to: 'pages#home'
  resources :listings
  resources :pets
  resources :bookings
  resources :users
  delete "/bookings/:id" => "bookings#destroy", as: 'delete_booking'

  resources :listings do
    resources :bookings, only: [:new, :show, :create, :destroy] do
      resources :reviews, only: [:new, :create, :show]
    end
  end


  resources :bookings, only: [:show] do
    member do
      post :accept
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  devise :database_authenticatable, :authentication_keys => [:email]
  validates :email, uniqueness: true
  validates :name, presence: true
  validates :surname, presence: true
  validates :avatar, presence: true
  has_many :pets
  has_one_attached :avatar
  has_many :listings
  has_many :reviews
  has_many :bookings, dependent: :destroy
  has_many :booked_listings, through: :bookings, source: :listing
  has_many :hosted_listings, class_name: 'Listing', dependent: :destroy
  has_many :my_reviews, through: :listings, source: :reviews, dependent: :destroy

   def requests # Booking request for meals I own
    Booking.joins(:listing).where('listings.user_id' => id).where(accepted: false)
   end

   def booking_info # Booking request for meals I own
    Booking.joins(:listing).where('listings.user_id' => id).where(accepted: true)
   end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController


  def dashboard
    @user = current_user
    @requests = @user.requests
    @booking_info = @user.booking_info
    @ongoing_bookings = @user.bookings.where(['ending_at >= ? and starting_at <= ? and accepted = true',  DateTime.now, DateTime.now])
    @upcoming_bookings = @user.bookings.where(['starting_at > ?',  DateTime.now])
    @expired_bookings = @user.bookings.where(['starting_at < ? and ending_at < ? and accepted = true', DateTime.now, DateTime.now]) + @user.bookings.where(['starting_at < ? and accepted = false', DateTime.now])

    @ongoing_hostings = @booking_info.where(['ending_at >= ? and starting_at <= ? and accepted = true',  DateTime.now, DateTime.now])
    @upcoming_hostings = @booking_info.where(['starting_at > ?',  DateTime.now])
    @expired_hostings = @booking_info.where(['starting_at < ? and ending_at < ? and accepted = true', DateTime.now, DateTime.now])

    @requests_to_accept = @requests.where(['starting_at >= ? and accepted = false',  DateTime.now])
    @expired_requests = @requests.where(['starting_at < ? and accepted = false', DateTime.now])

  end

  def show
    @user = User.find(params[:id])
    @average_user_rating = @user.my_reviews.average(:rating)
    @number_of_ratings = @user.my_reviews.count
  end

private

  def user_params
    params.require(:user).permit(:name, :surname, :email, :avatar)
  end

end

app/views/users/dashboard.html.erb
<div class="container container-dashboard">
  <div class="row">
    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-6 col-xl-6 dashboard-column left-column">
      <h5 class="title-cards">Ongoing bookings:</h5>
      <% if @ongoing_bookings.any? %>
        <% @ongoing_bookings.each do |booking| %>
          <%= link_to booking_path(booking.id) do  %>
            <div class="display link-to-card">
              <%= cl_image_tag(booking.pet.photo_url.key, height: 100, width: 100, class: 'radius') %>
              <p class="title-dashboard"><%= booking.listing.title %></p>
              <ul class="decription-dashboard list-unstyled">
                <li><i class="fas fa-calendar-alt"></i><%= booking.starting_at %> to <%= booking.ending_at %></li>
                <li><i class="fas fa-pound-sign"></i><%= (booking.ending_at - booking.starting_at).to_i * booking.listing.price_per_day.to_i %></li>
                <li><i class="fas fa-search-location"></i><%= booking.listing.location %></li>
                <li><i class="fas fa-user-alt"></i><%= booking.listing.user.name %> <%= booking.listing.user.surname %></li>
                <li><i class="fas fa-cat"></i><%= booking.pet.name %></li>
                <li><i class="fas fa-info-circle"></i><span class="dashboard-line-collapse"><%= booking.listing.description %></span></li>
              </ul>
              <%= cl_image_tag(booking.listing.photos.first.key, class: "img-dashboard img-ongoing") %>

              <div class="status-wrapper">
              <% if booking.accepted %>
                <div class="status accepted">Status: <i class="fas fa-check-circle"> (confirmed)</i></div>
              <% else %>
                <div class="status pending">Status: <i class="fas fa-clock"> (pending) </i></div>
              <% end %>
              </div>

            </div>
            <%end%>
          <%end%>
          <% else  %>
            <div class="no-content">
              <p>You don't have any ongoing bookings</p>
              <%= link_to "Explore", listings_path, class: "btn btn-show-more" %>
            </div>
          <% end %>


      <h5 class="title-cards">Your upcoming bookings:</h5>
      <% if @upcoming_bookings.any? %>
        <% @upcoming_bookings.each do |booking| %>
          <%= link_to booking_path(booking.id) do  %>
          <div class="display link-to-card">
            <%= cl_image_tag(booking.pet.photo_url.key, height: 100, width: 100, class: 'radius') %>
            <p class="title-dashboard"><%= booking.listing.title %></p>
            <ul class="decription-dashboard list-unstyled">
              <li><i class="fas fa-calendar-alt"></i><%= booking.starting_at %> to <%= booking.ending_at %></li>
              <li><i class="fas fa-pound-sign"></i><%= (booking.ending_at - booking.starting_at).to_i * booking.listing.price_per_day.to_i %></li>
              <li><i class="fas fa-search-location"></i><%= booking.listing.location %></li>
              <li><i class="fas fa-user-alt"></i><%= booking.listing.user.name %> <%= booking.listing.user.surname %></li>
              <li><i class="fas fa-cat"></i><%= booking.pet.name %></li>
              <li><i class="fas fa-info-circle"></i><span class="dashboard-line-collapse"><%= booking.listing.description %></span></li>
            </ul>
            <%= cl_image_tag(booking.listing.photos.first.key, class: "img-dashboard") %>
            <%= link_to "Cancel this booking",  delete_booking_path(booking), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-outline-danger btn-cancel" %>

          <div class="status-wrapper">
          <% if booking.accepted %>
            <div class="status accepted">Status: <i class="fas fa-check-circle"> (confirmed)</i></div>
          <% else %>
            <div class="status pending">Status: <i class="fas fa-clock"> (pending) </i></div>
          <% end %>
          </div>

          </div>
        <%end%>
      <%end%>
    <% else  %>
      <div class="no-content">
        <p>You don't have any upcoming bookings</p>
        <%= link_to "Explore", listings_path, class: "btn btn-show-more" %>
      </div>
    <% end %>

    <h5 class="title-cards">Your past bookings:</h5>

    <% if @expired_bookings.any? %>
      <% @expired_bookings.each do |booking| %>
        <%= link_to booking_path(booking.id) do  %>
        <div class="display link-to-card">
          <%= cl_image_tag(booking.pet.photo_url.key, height: 100, width: 100, class: 'radius') %>
          <p class="title-dashboard"><%= booking.listing.title %></p>
          <ul class="decription-dashboard list-unstyled">
            <li><i class="fas fa-calendar-alt"></i><%= booking.starting_at %> to <%= booking.ending_at %></li>
            <li><i class="fas fa-pound-sign"></i><%= (booking.ending_at - booking.starting_at).to_i * booking.listing.price_per_day.to_i %></li>
            <li><i class="fas fa-search-location"></i><%= booking.listing.location %></li>
            <li><i class="fas fa-user-alt"></i><%= booking.listing.user.name %> <%= booking.listing.user.surname %></li>
            <li><i class="fas fa-cat"></i><%= booking.pet.name %></li>
            <li><i class="fas fa-info-circle"></i><%= booking.listing.description %></li>
          </ul>
          <%= cl_image_tag(booking.listing.photos.first.key, class: "img-dashboard") %>
          <%if booking.reviews.any? == false && booking.accepted%>
            <%= link_to "Add a review", new_listing_booking_review_path(booking.listing_id, booking.id), class: "btn btn-outline-primary btn-cancel btn-review" %>
          <% elsif booking.reviews.any? == false && booking.accepted == false %>
            <p class="review-blocked"><i class="fas fa-exclamation-circle"></i>You can't review a booking that was not accepted</p>
          <%else%>
            <%= link_to "Show my review", listing_path(booking.listing_id), class: "btn btn-outline-success btn-cancel btn-review" %>
          <%end%>
          <div class="status-wrapper">
          <% if booking.accepted %>
            <div class="status accepted">Status: <i class="fas fa-check-circle"> (confirmed)</i></div>
          <% else %>
            <div class="status pending">Status: <i class="fas fa-clock"> (pending) </i></div>
          <% end %>
        </div>
      </div>
    <%end%>
  <%end%>
  <% else %>

  <div class="no-content">
    <p>You don't have any past bookings</p>
    <%= link_to "Explore", listings_path, class: "btn btn-show-more" %>
  </div>
  <% end %>
</div>





    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-6 col-xl-6 dashboard-column">
      <h5 class="title-cards">Ongoing hostings:</h5>
      <% if @ongoing_hostings.any?%>
        <% @ongoing_hostings.each do |l| %>
        <div class="display upcoming-hostings">
          <%= cl_image_tag(l.pet.photo_url.key, height: 100, width: 100, class: 'radius') %>
          <p class="title-dashboard"><%= l.listing.title %></p>
          <ul class="decription-dashboard list-unstyled">
            <li><i class="fas fa-calendar-alt"></i><%=l.starting_at%> to <%= l.ending_at%></li>
            <li><i class="fas fa-pound-sign"></i> <%= (l.ending_at - l.starting_at).to_i * l.listing.price_per_day.to_i %></li>
            <li class="link-to"><i class="fas fa-cat"></i>
            <%= link_to pet_path(l.pet.id) do  %>
              <%= l.pet.name %>
            <%end%>
            <%= link_to user_path(l.user.id) do  %>
              (owner: <%=l.user.name%>)</li>
            <%end%>
          </ul>
          <%= cl_image_tag(l.listing.photos.first.key, class: "img-dashboard") %>
        </div>
      <% end %>
      <% else %>
        <div class="no-content">
          <p>You are not currently hosting anybody.</p>
          <%= link_to "Create a new listing", new_listing_path, class: "btn btn-show-more" %>
        </div>
      <% end %>




      <h5 class="title-cards">Upcoming hostings:</h5>
        <% if @upcoming_hostings.any?%>
          <% @upcoming_hostings.each do |l| %>
            <div class="display upcoming-hostings">
              <%= cl_image_tag(l.pet.photo_url.key, height: 100, width: 100, class: 'radius') %>
              <p class="title-dashboard"><%= l.listing.title %></p>
              <ul class="decription-dashboard list-unstyled">
                <li><i class="fas fa-calendar-alt"></i><%=l.starting_at%> to <%= l.ending_at%></li>
                <li><i class="fas fa-pound-sign"></i> <%= (l.ending_at - l.starting_at).to_i * l.listing.price_per_day.to_i %></li>
                <li class="link-to"><i class="fas fa-cat"></i>
                <%= link_to pet_path(l.pet.id) do  %>
                  <%= l.pet.name %>
                <%end%>
                <%= link_to user_path(l.user.id) do  %>
                  (owner: <%=l.user.name%>)</li>
                <%end%>
              </ul>
              <%= cl_image_tag(l.listing.photos.first.key, class: "img-dashboard") %>
              <%= link_to "Cancel this booking",  delete_booking_path(l), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-outline-danger btn-cancel btn-upcoming-hosting"  %>
            </div>
          <% end %>
          <% else %>
          <div class="no-content">
            <p>You do not have any upcoming hostings</p>
            <%= link_to "Create a new listing", new_listing_path, class: "btn btn-show-more" %>
          </div>
          <% end %>


     <div class="col-xs-12 col-sm-12 col-md-12 col-lg-6 col-xl-6 right-column">
      <h5 class="title-cards">You hosted:</h5>
        <% if @expired_hostings.any?%>
          <% @expired_hostings.each do |l| %>
            <div class="display expired-hostings">
              <%= cl_image_tag(l.pet.photo_url.key, height: 100, width: 100, class: 'radius') %>
              <p class="title-dashboard"><%= l.listing.title %></p>
              <ul class="decription-dashboard list-unstyled">
                <li><i class="fas fa-calendar-alt"></i><%=l.starting_at%> to <%= l.ending_at%></li>
                <li><i class="fas fa-pound-sign"></i> <%= (l.ending_at - l.starting_at).to_i * l.listing.price_per_day.to_i %></li>
                <li class="link-to"><i class="fas fa-cat"></i>
                <%= link_to pet_path(l.pet.id) do  %>
                  <%= l.pet.name %>
                <%end%>
                <%= link_to user_path(l.user.id) do  %>
                  (owner: <%=l.user.name%>)</li>
                <%end%>
              </ul>
              <%= cl_image_tag(l.listing.photos.first.key, class: "img-dashboard") %>
            </div>
            <% end %>
            <% else %>
            <div class="no-content">
              <p>You haven't hosted anybody yet</p>
              <%= link_to "Create a new listing", new_listing_path, class: "btn btn-show-more" %>
            </div>
          <% end %>
        </div>
      </div>
    </div>


  <div class="requests">
    <%if @requests.any? %>

      <% if @requests_to_accept.any? %>
        <h5 class="title-cards incoming-cards">Incoming Requests:</h5>
        <% @requests_to_accept.each do |booking| %>
          <div class="display-requests">
            <p>
              <i class="fas fa-cat"></i><%= link_to pet_path(booking.pet.id) do  %><%= booking.pet.name %><%end%> (owner: <%= link_to user_path(booking.user.id) do  %><%= booking.user.name %> <%=booking.user.surname%> <%end%>) |
              <i class="fas fa-calendar-alt"></i> <%= booking.starting_at %> to <%= booking.ending_at %> |
              <i class="fas fa-pound-sign"></i><%= (booking.ending_at - booking.starting_at).to_i * booking.listing.price_per_day.to_i %>
            </p>
            <%= link_to "Confirm", accept_booking_path(booking), method: :post, data: { confirm: 'Are you sure?' }, class: 'btn btn-success btn-outline-radius' %>
          </div>
        <% end %>
      <%end%>

      <% if @expired_requests.any? %>
        <h5 class="title-cards incoming-cards">Expired Requests:</h5>
          <% @expired_requests.each do |booking| %>
          <div class="display-requests">
            <p>
              <i class="fas fa-cat"></i><%= link_to pet_path(booking.pet.id) do  %><%= booking.pet.name %><%end%> (owner: <%= link_to user_path(booking.user.id) do  %><%= booking.user.name %> <%=booking.user.surname%> <%end%>) |
              <i class="fas fa-calendar-alt"></i> <%= booking.starting_at %> to <%= booking.ending_at %> |
              <i class="fas fa-pound-sign"></i><%= (booking.ending_at - booking.starting_at).to_i * booking.listing.price_per_day.to_i %>
            </p>
            <%= link_to "Remove",  delete_booking_path(booking), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-outline-danger btn-outline-radius"  %>
          </div>
        <% end %>
      <%end%>

      <% elsif %>
      <div class="no-requests">
        <p>You don't have any incoming requests.</p>
       </div>

    </div>
    <%end%>

    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="profile">
  <div class="user-profile-wrapper">
    <%=cl_image_tag @user.avatar.key, class: "profile-photo"%>
      <div class="user-details">
        <div>
          <p class="name-surname"><%=@user.name%> <%=@user.surname%></p>
          <p class="user-small-font">Member since: <%=@user.created_at.strftime("%m/%Y")%></p>
            <div id="star-rating">
            <% if @user.my_reviews.blank? && @user == current_user%>
              <p class="user-no-rating"><i class="fas fa-exclamation-triangle"></i>You haven't been rated yet</p>
            <%  elsif @user.my_reviews.blank? %>
              <p class="user-no-rating"><i class="fas fa-exclamation-triangle"></i>This user hasn't been rated yet</p>
            <% else %>
              <% render_stars(@average_user_rating).each do |star| %>
                <%= image_tag(star, width: '24') %>
              <%end%>
            <p>average rating: <span><%= @average_user_rating %> (<%= @number_of_ratings %> reviews)</span> </p>
            <% end %>
            </div>
          </div>

          <% if @user == current_user%>
          <div class="add-buttons">
            <p class="user-small-font"><span>Your email:</span> <%=@user.email%></p>
            <%= link_to "Edit your profile", edit_user_registration_path, class: "btn btn-show-more" %>
            <%= link_to "Add a new listing", new_listing_path, class: "btn btn-show-more" %>
            <%= link_to "Add a new pet", new_pet_path, class: "btn btn-show-more" %>
          </div>
          <%else%>
          <div class="add-buttons">
            <%= mail_to @user.email, "Contact the user", class: "btn btn-show-more"%>
          </div>
          <%end%>
        </div>
      </div>



      <%if @user.pets.any?%>
        <%if @user == current_user%>
          <p class="title-user-profile-section">Your pets:</p>
        <%else%>
          <p class="title-user-profile-section"><%=@user.name%>'s pets:</p>
        <%end%>
        <div class="row user-row">
          <%@user.pets.each do |pet| %>
            <%= link_to pet_path(pet.id) do  %>
              <div class="col-xs-6 col-sm-6 col-md-4 col-lg-3 col-xl-3 user-pets-listings-card">
                <%= cl_image_tag(pet.photo_url.key) %>
                <p class="pet-name-card"><%=pet.name%></p>
              </div>
            <%end%>
          <%end%>
        </div>
        <%else%>
          <%if @user == current_user%>
            <p class="title-user-profile-section">Your pets:</p>
            <div class="no-requests no-pets-listings">
              <p>You do not have any pets</p>
            </div>
          <%else%>
          <p class="title-user-profile-section"><%=@user.name%>'s pets:</p>
          <div class="no-requests no-pets-listings">
            <p><%=@user.name%> doesn't have any pets</p>
          </div>
          <%end%>
        <%end%>

      <%if @user.listings.any?%>
        <%if @user == current_user%>
          <p class="title-user-profile-section">Your listings:</p>
        <%else%>
          <p class="title-user-profile-section"><%=@user.name%>'s listings:</p>
        <%end%>
        <div class="row user-row user-row-bottom">
          <%@user.listings.each do |listing| %>
          <%= link_to listing_path(listing.id) do  %>
          <div class="col-xs-6 col-sm-6 col-md-4 col-lg-3 col-xl-3 user-pets-listings-card">
            <%= cl_image_tag(listing.photos.first.key) %>
            <div class="user-listings-small-cards">
              <p class="small-cards-title"><%=listing.title%></p>
              <p class="small-card-detail"><i class="fas fa-search-location"></i><%=listing.location%></p>
              <p class="small-card-detail"><i class="fas fa-pound-sign"></i><%=listing.price_per_day%> per day</p>
            </div>
          </div>
          <%end%>
        <%end%>
        </div>
      <%else%>
        <%if @user == current_user%>
          <p class="title-user-profile-section">Your listings:</p>
          <div class="no-requests no-pets-listings no-pets-listings-last">
            <p>You do not have any listings</p>
          </div>
        <%else%>
          <p class="title-user-profile-section"><%=@user.name%>'s listings:</p>
          <div class="no-requests no-pets-listings no-pets-listings-last">
            <p><%=@user.name%> doesn't have any listings</p>
          </div>
        <%end%>
      <%end%>

</div>